export const coworkers = [
  {
    id: 1,
    fullName: 'Daniel Vanpalo',
    imgUrl: '/daniel.jpg',
    expertise: 'Frontend-utvecklare',
    phone: '0730-55 66 77',
    email: 'daniel@eldsit.se',
    techStack: '',
    shortBio:
      'Frontend-utvecklare med sinne för digitala lösningar och passion för kod samt stora intressen inom UX.',
    bio: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
  },
  {
    id: 2,
    fullName: 'Emil Helgesson',
    imgUrl: '/emil.jpg',
    expertise: 'Frontend-utvecklare',
    phone: '0730-55 66 77',
    email: 'emil@eldsit.se',
    techStack: '',
    shortBio:
      'Frontend-superstar med sinne för effektiv kodning med smarta  lösningar och passion för tillgänglighet till internet för alla samt gillar Bitcoin.',
    bio: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
  },
  {
    id: 3,
    fullName: 'Simon Bengtsson',
    imgUrl: 'simon.jpg',
    expertise: 'Backend-utvecklare',
    phone: '0730-55 66 77',
    email: 'simon@eldsit.se',
    techStack: '',
    shortBio:
      'Backend-virtuos med sinne för digitala lösningar och passion för kod samt snabba motorcyklar.',
    bio: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
  },
  {
    id: 4,
    fullName: 'Linus Hernvall',
    imgUrl: 'linus.jpg',
    expertise: 'Backend-utvecklare',
    phone: '0730-55 66 77',
    email: 'linus@eldsit.se',
    techStack: '',
    shortBio: 'Backend-fantom med läggning åt problemlösningar och ett stort hjärta för livemusik.',
    bio: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
  },
  {
    id: 5,
    fullName: 'Lucas Alfredsson',
    imgUrl: 'lucas.jpg',
    expertise: 'UX-designer',
    phone: '0730-55 66 77',
    email: 'lucas@eldsit.se',
    techStack: '',
    shortBio:
      'UX Designer med ett öga för detaljer och ett ständigt intresse att besöka nya platser på vår jord.',
    bio: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
  },
];
